### PR TITLE
ssh2-python next

### PR DESCRIPTION
**Pull request by enkore**
xref https://github.com/ParallelSSH/ssh2-python/pull/202

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@enkore Is your intention with this new organization to take over the pypi packages that are currently under the old org? (Specifically keeping the same names)

**Comment by enkore** [comment]
I believe the earliest eligibility date for starting that process would be late 2024. So the next best thing is making new names and assigning them to a PyPI org or at least multiple maintainers to avoid the _unit bus factor_.

**Comment by JacobCallahan** [comment]
@enkore I'm not sure if you've seen, but I've already published an alternate (ssh2-python312 (nasty, i know)) to pypi in the meantime based on my fork.
Also, in my fork, I switched to github actions for the build/publish process instead of relying on CircleCI. I'd recommend the same for these.

Perhaps a way forward would be to get all of this in place to replace the current packages around when Python 3.13 drops in October. In the meantime, you can push alternative versions for ssh-python and parallel-ssh. I can help with some light maintenance, but with the switch to github actions, those tasks should be light.

If that sounds good to you, then I'll accept the invite into this new organization. Otherwise, I can't promise the time investment needed for a more involved role.

**Comment by enkore** [comment]
Sounds good to me!

**Pull request merged**
